# Site
title:              Reinold Carrasco
bio:                'Experienced Android Developer with a demonstrated history of working in the information technology and services industry. Skilled in SQL, Data Analysis, SQLite, Eclipse, and Xamarin. Strong engineering professional with a Licentiate degree focused in Information Technology from Universidad del Caribe, Dominican Republic.'
description:        " "
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://rcarrascof.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   rcarrasco

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              rcarrascof@outlook.com
twitter:            ByReinold
facebook:           ReinoldC
github-url:         rcarrascof
stackoverflow:      8339006/rcarrasco   from a "https://stackoverflow.com/users/8339006/rcarrasco" link
linkedin:           reinoldcarrasco
#xing:              username
instagram:          ByReinold
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
